### ISSUE TITLE
anova returns error message

### ISSUE THREAD

**Issue by MarkTrinder** [lindesaysh/MRSea#1]
Hi Lindesay

I am getting the following error with _anova:_

> anova(bestModel)
Error in solve.default(vbeta[zeroidx, zeroidx, drop = FALSE]) : 
  system is computationally singular: reciprocal condition number = 7.78779e-17

I think the model is fitting ok otherwise - summary(bestModel) works ok - see below:

> bestModel=make.gamMRSea(salsa2dOutput$bestModel)
> summary(bestModel)

Call:
gamMRSea(formula = response ~ bs(Depth, knots = splineParams[[2]]$knots, 
    degree = splineParams[[2]]$degree, Boundary.knots = splineParams[[2]]$bd) + 
    bs(Dist.to.coast, knots = splineParams[[3]]$knots, degree = splineParams[[3]]$degree, 
        Boundary.knots = splineParams[[3]]$bd) + LocalRadialFunction(radiusIndices, 
    dists, radii, aR) + offset(log(area)), family = quasipoisson(link = log), 
    data = data2, splineParams = splineParams)

Deviance Residuals: 
   Min      1Q  Median      3Q     Max  
-1.267  -0.747  -0.454   0.395   2.390  

Coefficients:
                    Estimate Std. Error Robust S.E. t value Pr(>|t|)    
(Intercept)         1.27e+01   3.10e+00    4.05e+00    3.14  0.00172 ** 
s(Depth)1          -1.73e+00   9.29e-01    6.15e-01   -2.82  0.00496 ** 
s(Depth)2          -1.26e+00   1.02e+00    8.64e-01   -1.46  0.14352    
s(Depth)3          -1.47e+00   9.43e-01    6.80e-01   -2.16  0.03122 *  
s(Dist.to.coast)1   2.56e+00   1.73e+00    2.62e+00    0.98  0.32899    
s(Dist.to.coast)2   3.03e+04   6.56e+03    8.23e+03    3.68  0.00024 ***
s(Dist.to.coast)3  -8.80e+08   1.39e+08    1.93e+08   -4.56  5.6e-06 ***
s(x.pos, y.pos)b1   2.84e+00   5.04e-01    7.00e-01    4.06  5.2e-05 ***
s(x.pos, y.pos)b2   1.24e+01   2.47e+00    3.57e+00    3.48  0.00052 ***
s(x.pos, y.pos)b3  -4.67e+01   7.02e+00    1.00e+01   -4.65  3.6e-06 ***
s(x.pos, y.pos)b4   4.72e+01   7.09e+00    1.06e+01    4.47  8.8e-06 ***
s(x.pos, y.pos)b5   2.62e+00   4.82e-01    6.76e-01    3.87  0.00011 ***
s(x.pos, y.pos)b6  -3.09e+01   7.28e+00    1.03e+01   -2.99  0.00282 ** 
s(x.pos, y.pos)b7   5.44e+00   4.80e+00    6.72e+00    0.81  0.41825    
s(x.pos, y.pos)b8   1.46e+00   5.85e-01    5.10e-01    2.86  0.00435 ** 
s(x.pos, y.pos)b9  -1.47e+01   2.56e+00    3.11e+00   -4.73  2.5e-06 ***
s(x.pos, y.pos)b10  8.12e+00   3.81e+00    5.51e+00    1.47  0.14078    
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

(Dispersion parameter for quasipoisson family taken to be 0.688)

    Null deviance: 869.67  on 1189  degrees of freedom
Residual deviance: 686.17  on 1173  degrees of freedom
AIC:  NA

Max Panel Size = 64; Number of panels = 28
Number of Fisher Scoring iterations: 6

**Comment by lindesaysh** [comment]
Hi Mark,

It looks to me like there might be a problem with Distance to Coast (a couple of extremely large standard errors).  I would suggest removing this term and seeing if you have the same problem.  I would be concerned that distance to coast and the spatial smooth may be rather confounded, or that for distance from coast you have no animals farthest from the coast and therefore the variance is hard to estimate (hence large s.e.'s).

Hope this helps and let me know if it solves the problem.

Lindesay
