### ISSUE TITLE
anova not working & how to interpret outputs for models with different knots for different levels of spatial interaction

### ISSUE THREAD

**Issue by MarkTrinder** [lindesaysh/MRSea#13]
hi
the anova command doesn't seem to be working - I think its a naming error. Here is the error message:

Error in bs(dist.to.coast, knots = splineParams[[3]]$knots, degree = splineParams[[3]]$degree,  : 
  could not find function "bs"

Also, I understand how to interpret the terms in the standard before/after impact model - if the impact is sig. then indicates overall abundance change and if the interaction between impact & spatial term is sig. then indicates a spatially explicit abundance change.
But how do you interpret the terms when you specify separate knot allocation for each level of the impact term? In this model there is no interaction term (that I can identify in summary) so I am not sure how to determine if the change is spatially explicit or general.
thanks

**Comment by lindesaysh** [comment]
Hi Mark,

I think it looks like you might need to load the splines package as thats where the bs function sits.  

To answer your second question, i suppose you could fit a model with the "interaction" as you have specified and one with no interaction term (e.g. impact + s(x,y)) and use a fit criterion to choose between the two.  if you find that the more complex model is preferred then there must be some improvement by allowing the flexibility to change among impact levels. You could check where the knots are in each and see how that changes the spatial distribution.   Lastly you could look at spatially explicit differences and see if you can identify any significant changes in spatial distribution (using the bootstraps to determine significance). 

I hope that helps,
Thanks,
Lindesay

**Comment by MarkTrinder** [comment]
thanks for speedy response.

splines loaded and working now, ta.

and thanks for the advice on model selection - I was hoping there might be an easy way to extract the information from the model that I had not managed to figure out, but I can work through the steps you suggest instead.
