### ISSUE TITLE
tibble issue in create.bootstrap.data

### ISSUE THREAD

**Issue by lindesaysh** [lindesaysh/MRSea#20]
either make code for tibble or convert input to data frame if tibble detected.

**Comment by CamBullen** [comment]
Potentially a similar issue in the plotCumRes function. 

If a tibble is used to fit a model, then it seems a tibble is returned by model.fit$data. This creates an error on line 65 of the plotCumRes code because covardat is not a numeric vector as needed by stats::quantile .

**Comment by lindesaysh** [comment]
Hi Cameron,
Thanks for letting me know about this issue.  I have added a few lines in the plotCumRes and create.bootstrap.data functions that should stop this issue.  I have also ensured that the data attached to the model objects returned from runSALSA1D and runSALSA2D are data frames even if the initial model had tibble data.  These updates are on the master/development branch if you wish to update.  Let me know if you still have issues. 
Thanks,
Lindesay
