### ISSUE TITLE
Website - broken pages for vignettes

### ISSUE THREAD

**Issue by CamBullen** [lindesaysh/MRSea#26]
Hi Lindesay, thanks for all your work building/maintaining/updating MRSea! Just in case you hadn't realized, I wanted to flag that several of the vignette pages on the new website don't seem to be functioning ("Page not found (404)" error message). 

The error seems to occur for:
- 1D Smooths (http://lindesaysh.github.io/MRSea/articles/web/GettingStarted_1Dsmoothing.html)
- 2D Smooths (http://lindesaysh.github.io/MRSea/articles/web/GettingStarted_2Dsmoothing.html)
- Using Different Splines (http://lindesaysh.github.io/MRSea/articles/web/FittingDifferentSplines_MRSea_v1.3.Rmd.html)
- Publications (http://lindesaysh.github.io/MRSea/articles/web/publications.html)

The other vignettes (2D Interaction, Renewables case study) seem to be fine. Thanks again!

**Comment by lindesaysh** [comment]
Gah!  Thank you for letting me know.  I'll see if i can fix those up.

**Comment by lindesaysh** [comment]
all fixed.  links work now.
