### ISSUE TITLE
Mismatch in data sizes predict.gamMRSea()

### ISSUE THREAD

**Issue by grwhumphries** [lindesaysh/MRSea#8]
In predict.gamMRSea() there seems to be an issue if your newdata is not the same length (nrows) as the object's (model object) fitted data. 

```
predict.gamMRSea<- function (newdata=NULL, g2k=NULL, object, type = "response",coeff = NULL)
{
  # attributes(model$formula)$.Environment <- environment()
  # radii <- splineParams[[1]]$radii
  # radiusIndices <- splineParams[[1]]$radiusIndices
  # dists <- g2k
  
  splineParams <- object$splineParams

  newdata <- object$data  #### 

  ...
}
```
newdata is being overwritten here by object$data. Could this use an if statement?

```
if(newdata == NULL){
     newdata <- object$data
}

```

Cheers

**Comment by lindesaysh** [comment]
Hi Grant,

Gosh thanks for spotting that.  It has come from a recent merge and I am still using the previous iteration on my machine.  It should be all updated now.  Please let me know if you have any other issues. 

Cheers,
Lindesay
