### ISSUE TITLE
runInfluence (and timeinfluencecheck)

### ISSUE THREAD

**Issue by MarkTrinder** [lindesaysh/MRSea#9]
this code doesn't seem to work - its seems to be in the 'update' model section:
Error in MRSea::model.frame.gamMRSea(formula = response ~ as.factor(survey.no) +  : 
  variable lengths differ (found for 'LRF.g(radiusIndices, dists, radii, aR)')

I have checked and I think the id and iduse variables may have been mixed up? (at least in the time check version), but having fiddled with that and fixed it (at least as far as I can tell: the new input data are all the same size) I still get the above error.

any thoughts?

**Comment by lindesaysh** [comment]
Hi Mark,
Could you let me know what version of MRSea you are using and or when you last downloaded it.  Also, could you give me a reproducible example so that I can debug your issue. 
Thanks,
Lindesay

**Comment by lindesaysh** [comment]
Issue fixed.  
New MRSea release 1.02
